### ISSUE TITLE
Mejorar las vistas

### ISSUE THREAD

**Issue by juanbono** [dds-frd-utn/medicina-delta#5]
<h2>Mejorar las vistas</h2>

<h3>Prioridad: Media</h3>

<h3>Diversión: Alta</h3>

<h3>Descripción:</h3>

Las vistas entregadas junto a la documentación dejaban espacio para la mejora de las mismas.
Mejorar el aspecto de las vistas y lograr que mantengan un aspecto uniforme.

**Comment by martindegesus** [comment]
A la orden comandante Bono
